import { FileType } from '../../../types'

export type ParserType =
  | 'brigadier:bool'
  | 'brigadier:double'
  | 'brigadier:float'
  | 'brigadier:integer'
  | 'brigadier:string%greedy'
  | 'brigadier:string%phrase'
  | 'brigadier:string%word'
  | 'minecraft:angle'
  | 'minecraft:block_pos'
  | 'minecraft:block_predicate'
  | 'minecraft:block_state'
  | 'minecraft:color'
  | 'minecraft:column_pos'
  | 'minecraft:component'
  // | 'minecraft:dimension'
  | 'minecraft:entity%entities%multiple'
  | 'minecraft:entity%entities%single'
  | 'minecraft:entity%players%multiple'
  | 'minecraft:entity%players%single'
  | 'minecraft:entity_anchor'
  // | 'minecraft:function'
  | 'minecraft:game_profile'
  | 'minecraft:gamemode'
  | 'minecraft:heightmap'
  | 'minecraft:int_range'
  | 'minecraft:item_predicate'
  | 'minecraft:item_slot'
  | 'minecraft:item_stack'
  | 'minecraft:message'
  | 'minecraft:nbt_compound_tag'
  | 'minecraft:nbt_path'
  | 'minecraft:nbt_tag'
  | 'minecraft:objective'
  | 'minecraft:objective_criteria'
  | 'minecraft:operation'
  | 'minecraft:particle'
  | 'minecraft:resource%minecraft:attribute'
  | 'minecraft:resource%minecraft:damage_type'
  | 'minecraft:resource%minecraft:enchantment'
  | 'minecraft:resource%minecraft:entity_type'
  | 'minecraft:resource%minecraft:mob_effect'
  // | 'minecraft:resource%minecraft:worldgen/biome'
  // | 'minecraft:resource_key%minecraft:worldgen/configured_feature'
  // | 'minecraft:resource_key%minecraft:worldgen/structure'
  // | 'minecraft:resource_key%minecraft:worldgen/template_pool'
  | 'minecraft:resource_location'
  // | 'minecraft:resource_or_tag%minecraft:worldgen/biome'
  | 'minecraft:resource_or_tag%minecraft:point_of_interest_type'
  // | 'minecraft:resource_or_tag_key%minecraft:worldgen/structure'
  | 'minecraft:rotation'
  | 'minecraft:score_holder%multiple'
  | 'minecraft:score_holder%single'
  | 'minecraft:scoreboard_slot'
  | 'minecraft:style'
  | 'minecraft:swizzle'
  | 'minecraft:team'
  | 'minecraft:template_mirror'
  | 'minecraft:template_rotation'
  | 'minecraft:time'
  | 'minecraft:uuid'
  | 'minecraft:vec2'
  | 'minecraft:vec3'
  | FileType
  | 'mcdu:unknown'

export function isFileType(type: ParserType): type is FileType {
  return !type.includes(':')
}